Rewrite http emojis api
l7ssha/nyxx pull request #491
Opened 2023-06-12 15:12 UTC by Lexedia

# Description
Rewrite the http emojis api.

TODO: Tests

## Connected issues & other potential problems
Closes #458

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

2023-06-12 17:49 UTC, abitofevrything requested changes

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/http/managers/emoji_manager.dart
> +  Future<List<Emoji>> fetchAll() async {
This should be named `list()`

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/http/managers/message_manager.dart
> +
The logic of choosing whether to parse as a text or guild emoji should be moved to the `parse` method of `EmojiManager` - see `ChannelManager.parse` for an example.

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/http/managers/message_manager.dart
> +  }
These methods should take a `ReactionBuilder` instead of a String that is then encoded. Makes it much safer,

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/manager_mixin.dart
> +  ClientEmojiManager get emojis => ClientEmojiManager(this as NyxxRest, guilds.cache.values.map((g) => g.emojis));
Again I don't think this is a good idea - this has multiple issues relating to caching.

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/models/emoji/emoji.dart
> +}
I feel like this class should be at the other end of the class hierarchy - `PartialEmoji <- Emoji <- (TextEmoji, GuildEmoji)`. Then we can use `Emoji` as the type where we know it is *some* emoji and a more specific type if applicable.

2023-06-12 17:49 UTC, abitofevrything commented on lib/src/models/emoji/emoji.dart
> +  String toString() => '<${isAnimated != null && isAnimated! ? 'a' : ''}:$name:$id>';
Only override `defaultToString()` as `toString()` is handled by `SnowflakeEntity`, see the docs on `ToStringHelper` for more info.

2023-06-12 21:05 UTC, Rapougnac commented on lib/src/http/managers/emoji_manager.dart
> +}
What would the alternative be? I personally feel it's kind of a hassle when dealing with guilds and emojis.

2023-06-18 12:24 UTC, abitofevrything approved these changes

2023-06-20 14:42 UTC, l7ssha commented on lib/src/http/managers/emoji_manager.dart
> +    }
else is redundant here. just leave return as the last  statement

2023-06-20 14:44 UTC, l7ssha approved these changes

2023-06-20 14:45 UTC, merged